### ISSUE TITLE
Starting a simple tunnel

### ISSUE THREAD

**Issue by whyscream** [ngrok/ngrok-api-python#18]
Just found this repo / pypi package. Really nice to see this available.

Just one minor question, since the documentation is quite technical, and does not refer to functionality but only to technical features.
I want to use this library to create a tunnel like I do during normal development on a daily basis, using the cli: `ngrok http 5000`. But I cannot find the actual endpoint that I need to use for that. Is this even possible, or is there more to it?

**Comment by inconshreveable** [comment]
hey @whyscream this library is purely about making requests to the ngrok HTTP API: https://ngrok.com/docs/api

we're working on a separate package which will allow you to programmatically start tunnels which will have its own repo and package
